### ISSUE TITLE
randtoolkit module

### ISSUE THREAD

**Issue by Zephyrasgit** [pwwl/enhanced-binary-diversification#2]
Hi, I'm trying to create CFGs of executables using IDA Pro, with the codes provided in `enhanced-binary-diversification/enhanced-binary-randomization/orp/`. However, even after ensuring that I installed everything according to `README-Pappas.txt`, running `python test.py` gives me an import error, with python complaining that there is no module called `randtoolkit`. I have searched for this package to no avail. Are you able to let me know if this is something you/the original authors have created, and is it possible to provide this toolkit as well? Thanks!

**Comment by keenlooks** [comment]
randtoolkit.py is in the repo in a different folder:

https://github.com/pwwl/enhanced-binary-diversification/blob/main/enhanced-binary-randomization/randtoolkit.py

I have never messed with test.py in orp/ so not sure what way to get it to see randtoolkit... maybe explicitly add the above directory to the path for it? Did you try orp,py to create the CFG files?
