### ISSUE TITLE
Executable file after the binary transformation crashes

### ISSUE THREAD

**Issue by judowha** [pwwl/enhanced-binary-diversification#3]
Hi, I am trying run the example the caffeine.exe using only `'equiv', 'swap', 'preserv', 'reorder'`. I feed the transformed file into Cuckoo but it seems that the transformed file crushes. Here is the screenshot: 
![Screenshot from 2023-08-23 09-17-58](https://github.com/pwwl/enhanced-binary-diversification/assets/60347669/244f1315-4f5d-475e-b0a3-353fc905e1ba)
I tried several times and I found that once I include `disp`, the generated file is able to pass the Cuckoo analysis. 
Also, if I command these two lines in the `binary_transform.py`, the generated file is also executable. 
![Screenshot from 2023-08-23 09-22-37](https://github.com/pwwl/enhanced-binary-diversification/assets/60347669/33fd7311-722d-4313-ac27-1e0af4470cbe)
May I ask what are the propose of these two lines since the `adj_pe` is not used in other place within the code? Also, can I just jump these two lines if I don't include `disp` in the `ALLOWED_TRANSFORMS`? 
Looking forward to your reply. Thank you!

**Comment by keenlooks** [comment]
Thanks for the investigation!

To ensure I understand the issue, it seems like if you modify https://github.com/pwwl/enhanced-binary-diversification/blob/main/binary_transform.py#L31 to exclude `'disp','semnops'` then caffeine.exe crashes. However, if you then also comment out lines 156 and 157, then the resultant caffeine.exe executes as expected. Is this correct?

**Comment by judowha** [comment]
Thanks for your reply, and yes, this is exactly what I want to describe. 
Can you try to reproduce it on your side and see whether the same issue happens?

**Comment by keenlooks** [comment]
I think the latest commit (586777a) should fix this issue. Could you try it out please?

**Comment by judowha** [comment]
Yes, the issue is solved. Thanks for your help!!
